main: rx.rext.PeSy
version: 1.0.0
name: PerkSystem
author: RextDev
api-version: 1.21

commands:
  miplugin:
    description: Comando test
    aliases:
      - rextdev
  pesy:
    description: Perk system ADMIN
    permission: pesy.command.admin
    usage: /<command> <subcommand>
  perk:
    description: perks command
    permission: pesy.command.perk
    usage: /<command> <subcommand>

permissions:
  pesy.*:
    description: Usar todos las funciones
    default: op
    children:
      pesy.command: true
  pesy.command:
    description: Usar todos las funciones
    children:
      pesy.command.perk: true
      pesy.command.admin: true
    default: op
  pesy.command.perk:
    description: perks commands
    default: true
  pesy.command.admin:
    description: ADMINCOMMANDS
    default: op



# This set optional Dependency
softdepend: [PlaceholderAPI]